# Site settings
title: It Doesn't Look Like a Computer
description: A blog about embedded computing, IoT and programming any kind of device.
cover: assets/images/cover.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
baseurl: /
url: https://vminute.github.io/ # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
twitter: VMinute
github:  VMinute

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: "'UA-116691268-1"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: VMinute #github username
repo: vminute.github.io #github repository
branch: master #branch
relative_source: ../hanuman/ #source directory
destination: ../hanuman-pages/ #destination directory
production_url:  https://samanyougarg.com/
source_url:  https://github.com/samanyougarg/hanuman #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml